# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  start:
    cmds:
      - docker run -it --rm -p 8888:8888 -v "${PWD}":/home/jovyan/ quay.io/jupyter/datascience-notebook:2024-10-07
    silent: true
